AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/dummy/**/*"
