
default_count: 10
models:
  user:
    count: 5
    attributes:
      name: "User {{index}}"
      email: "user{{index}}@example.com"
    disabled_fields: [nickname, password password_digest]
  post:
    count: 5
    attributes:
      title: "Post {{index}}"