default_count: 5
models:
  user:
    attributes:
      name: "name {{index}}"
      email: "email {{index}}"
    disabled_fields: []
  post:
    attributes:
      title: "title {{index}}"
    disabled_fields: []
  comment:
    attributes:
    disabled_fields: []
